Dir {
  ArchiveDir ".";
};

APT::FTPArchive::DoByHash "true";

BinDirectory "pool/main" {
  Packages "dists/trixie/main/binary-armel/Packages";
};

APT::FTPArchive::Release {
  Origin "WMT OS";
  Label "WMT OS";
  Suite "trixie";
  Codename "trixie";
  Architectures "armel";
  Components "main";
  Description "WMT OS package archive";
};
